08:10:37.705 logback [Curator-Framework-0] WARN  org.apache.curator.ConnectionState - Connection attempt unsuccessful after 32964647 (greater than max timeout of 60000). Resetting connection and trying again with a new connection.
08:10:38.250 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server 192.168.144.130/192.168.144.130:2181. Will not attempt to authenticate using SASL (unknown error)
08:10:38.256 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] WARN  org.apache.zookeeper.ClientCnxn - Client session timed out, have not heard from server in 32963738ms for sessionid 0x1000005358d053f
08:10:38.486 logback [Curator-Framework-0] INFO  org.apache.zookeeper.ZooKeeper - Session: 0x1000005358d053f closed
08:10:38.486 logback [Curator-Framework-0-EventThread] INFO  org.apache.zookeeper.ClientCnxn - EventThread shut down for session: 0x1000005358d053f
08:10:38.487 logback [Curator-Framework-0] INFO  org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=192.168.144.130:2181 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@12010fd1
08:10:38.696 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server 192.168.144.130/192.168.144.130:2181. Will not attempt to authenticate using SASL (unknown error)
08:10:39.505 logback [Curator-Framework-0] ERROR o.a.c.f.imps.CuratorFrameworkImpl - Background operation retry gave up
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkBackgroundRetry(CuratorFrameworkImpl.java:728)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:857)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:809)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:64)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:267)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
08:10:39.505 logback [Curator-Framework-0] ERROR o.a.c.f.imps.CuratorFrameworkImpl - Background retry gave up
org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:838)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:809)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:64)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:267)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
08:10:43.543 logback [Curator-Framework-0] ERROR org.apache.curator.ConnectionState - Connection timed out for connection string (192.168.144.130:2181) and timeout (5000) / elapsed (5811)
org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:225)
	at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:94)
	at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:117)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:835)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:809)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:64)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:267)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
08:10:44.548 logback [Curator-Framework-0] ERROR org.apache.curator.ConnectionState - Connection timed out for connection string (192.168.144.130:2181) and timeout (5000) / elapsed (6819)
org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:225)
	at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:94)
	at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:117)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:835)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:809)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:64)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:267)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
08:10:44.549 logback [Curator-Framework-0] INFO  o.a.c.f.state.ConnectionStateManager - State change: LOST
08:10:44.549 logback [Curator-Framework-0] ERROR o.a.c.f.imps.CuratorFrameworkImpl - Background operation retry gave up
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkBackgroundRetry(CuratorFrameworkImpl.java:728)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:857)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:809)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:64)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:267)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
08:10:44.550 logback [Curator-Framework-0] ERROR o.a.c.f.imps.CuratorFrameworkImpl - Background retry gave up
org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:225)
	at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:94)
	at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:117)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:835)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:809)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:64)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:267)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
08:10:48.115 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] INFO  org.apache.zookeeper.ClientCnxn - Socket connection established to 192.168.144.130/192.168.144.130:2181, initiating session
08:10:48.118 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] INFO  org.apache.zookeeper.ClientCnxn - Session establishment complete on server 192.168.144.130/192.168.144.130:2181, sessionid = 0x1000005358d054c, negotiated timeout = 40000
08:10:48.118 logback [Curator-Framework-0-EventThread] INFO  o.a.c.f.state.ConnectionStateManager - State change: RECONNECTED
12:38:14.451 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x1000005358d054c for server 192.168.144.130/192.168.144.130:2181, unexpected error, closing socket connection and attempting reconnect
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:68)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
12:38:14.631 logback [Curator-Framework-0-EventThread] INFO  o.a.c.f.state.ConnectionStateManager - State change: SUSPENDED
12:38:15.638 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server 192.168.144.130/192.168.144.130:2181. Will not attempt to authenticate using SASL (unknown error)
12:38:15.643 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x1000005358d054c for server null, unexpected error, closing socket connection and attempting reconnect
java.net.NoRouteToHostException: No route to host: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
13:07:59.537 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server 192.168.144.130/192.168.144.130:2181. Will not attempt to authenticate using SASL (unknown error)
13:07:59.540 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x1000005358d054c for server null, unexpected error, closing socket connection and attempting reconnect
java.net.NoRouteToHostException: No route to host: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
13:08:00.507 logback [Curator-Framework-0] WARN  org.apache.curator.ConnectionState - Connection attempt unsuccessful after 1784916 (greater than max timeout of 60000). Resetting connection and trying again with a new connection.
13:08:01.237 logback [Curator-Framework-0] INFO  org.apache.zookeeper.ZooKeeper - Session: 0x1000005358d054c closed
13:08:01.239 logback [Curator-Framework-0] INFO  org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=192.168.144.130:2181 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@12010fd1
13:08:01.238 logback [Curator-Framework-0-EventThread] INFO  org.apache.zookeeper.ClientCnxn - EventThread shut down for session: 0x1000005358d054c
13:08:01.598 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server 192.168.144.130/192.168.144.130:2181. Will not attempt to authenticate using SASL (unknown error)
13:08:01.602 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.NoRouteToHostException: No route to host: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
13:08:02.317 logback [Curator-Framework-0] ERROR o.a.c.f.imps.CuratorFrameworkImpl - Background operation retry gave up
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkBackgroundRetry(CuratorFrameworkImpl.java:728)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:857)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:809)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:64)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:267)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
13:08:02.322 logback [Curator-Framework-0] ERROR o.a.c.f.imps.CuratorFrameworkImpl - Background retry gave up
org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:838)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:809)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:64)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:267)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
13:08:02.770 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server 192.168.144.130/192.168.144.130:2181. Will not attempt to authenticate using SASL (unknown error)
13:08:04.086 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.NoRouteToHostException: No route to host: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
13:08:05.187 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server 192.168.144.130/192.168.144.130:2181. Will not attempt to authenticate using SASL (unknown error)
13:08:06.370 logback [Curator-Framework-0] ERROR org.apache.curator.ConnectionState - Connection timed out for connection string (192.168.144.130:2181) and timeout (5000) / elapsed (5861)
org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:225)
	at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:94)
	at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:117)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:835)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:809)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:64)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:267)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
13:08:07.372 logback [Curator-Framework-0] ERROR org.apache.curator.ConnectionState - Connection timed out for connection string (192.168.144.130:2181) and timeout (5000) / elapsed (6865)
org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:225)
	at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:94)
	at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:117)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:835)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:809)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:64)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:267)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
13:08:07.373 logback [Curator-Framework-0] INFO  o.a.c.f.state.ConnectionStateManager - State change: LOST
13:08:07.373 logback [Curator-Framework-0] ERROR o.a.c.f.imps.CuratorFrameworkImpl - Background operation retry gave up
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkBackgroundRetry(CuratorFrameworkImpl.java:728)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:857)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:809)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:64)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:267)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
13:08:07.373 logback [Curator-Framework-0] ERROR o.a.c.f.imps.CuratorFrameworkImpl - Background retry gave up
org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:225)
	at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:94)
	at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:117)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:835)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:809)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:64)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:267)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
13:08:18.392 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] INFO  org.apache.zookeeper.ClientCnxn - Socket connection established to 192.168.144.130/192.168.144.130:2181, initiating session
13:08:18.399 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] INFO  org.apache.zookeeper.ClientCnxn - Session establishment complete on server 192.168.144.130/192.168.144.130:2181, sessionid = 0x1000005358d0567, negotiated timeout = 40000
13:08:18.399 logback [Curator-Framework-0-EventThread] INFO  o.a.c.f.state.ConnectionStateManager - State change: RECONNECTED
13:52:26.705 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x1000005358d0567 for server 192.168.144.130/192.168.144.130:2181, unexpected error, closing socket connection and attempting reconnect
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:68)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
13:52:26.890 logback [Curator-Framework-0-EventThread] INFO  o.a.c.f.state.ConnectionStateManager - State change: SUSPENDED
13:52:27.922 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server 192.168.144.130/192.168.144.130:2181. Will not attempt to authenticate using SASL (unknown error)
13:52:27.925 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x1000005358d0567 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.NoRouteToHostException: No route to host: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
13:52:29.763 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server 192.168.144.130/192.168.144.130:2181. Will not attempt to authenticate using SASL (unknown error)
15:28:08.370 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x1000005358d0567 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.NoRouteToHostException: No route to host: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
15:28:08.376 logback [Curator-Framework-0] WARN  org.apache.curator.ConnectionState - Connection attempt unsuccessful after 5741486 (greater than max timeout of 60000). Resetting connection and trying again with a new connection.
15:28:08.500 logback [Curator-Framework-0] INFO  org.apache.zookeeper.ZooKeeper - Session: 0x1000005358d0567 closed
15:28:08.500 logback [Curator-Framework-0] INFO  org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=192.168.144.130:2181 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@12010fd1
15:28:08.501 logback [Curator-Framework-0-EventThread] INFO  org.apache.zookeeper.ClientCnxn - EventThread shut down for session: 0x1000005358d0567
15:28:08.760 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server 192.168.144.130/192.168.144.130:2181. Will not attempt to authenticate using SASL (unknown error)
15:28:09.544 logback [Curator-Framework-0] ERROR o.a.c.f.imps.CuratorFrameworkImpl - Background operation retry gave up
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkBackgroundRetry(CuratorFrameworkImpl.java:728)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:857)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:809)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:64)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:267)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
15:28:09.546 logback [Curator-Framework-0] ERROR o.a.c.f.imps.CuratorFrameworkImpl - Background retry gave up
org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:838)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:809)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:64)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:267)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
15:28:11.995 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] INFO  org.apache.zookeeper.ClientCnxn - Socket connection established to 192.168.144.130/192.168.144.130:2181, initiating session
15:28:12.001 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] INFO  org.apache.zookeeper.ClientCnxn - Session establishment complete on server 192.168.144.130/192.168.144.130:2181, sessionid = 0x1000005358d0571, negotiated timeout = 40000
15:28:12.002 logback [Curator-Framework-0-EventThread] INFO  o.a.c.f.state.ConnectionStateManager - State change: RECONNECTED
17:05:57.529 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x1000005358d0571 for server 192.168.144.130/192.168.144.130:2181, unexpected error, closing socket connection and attempting reconnect
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:68)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
17:05:57.981 logback [Curator-Framework-0-EventThread] INFO  o.a.c.f.state.ConnectionStateManager - State change: SUSPENDED
17:05:59.209 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server 192.168.144.130/192.168.144.130:2181. Will not attempt to authenticate using SASL (unknown error)
17:05:59.214 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x1000005358d0571 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.NoRouteToHostException: No route to host: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
17:06:00.442 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server 192.168.144.130/192.168.144.130:2181. Will not attempt to authenticate using SASL (unknown error)
17:06:00.446 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x1000005358d0571 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.NoRouteToHostException: No route to host: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
18:18:58.765 logback [Curator-Framework-0] WARN  org.apache.curator.ConnectionState - Connection attempt unsuccessful after 4380752 (greater than max timeout of 60000). Resetting connection and trying again with a new connection.
18:18:59.441 logback [Curator-Framework-0] INFO  org.apache.zookeeper.ZooKeeper - Session: 0x1000005358d0571 closed
18:18:59.443 logback [Curator-Framework-0] INFO  org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=192.168.144.130:2181 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@12010fd1
18:18:59.445 logback [Curator-Framework-0-EventThread] INFO  org.apache.zookeeper.ClientCnxn - EventThread shut down for session: 0x1000005358d0571
18:18:59.960 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server 192.168.144.130/192.168.144.130:2181. Will not attempt to authenticate using SASL (unknown error)
18:18:59.972 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.NoRouteToHostException: No route to host: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
18:19:00.506 logback [Curator-Framework-0] ERROR o.a.c.f.imps.CuratorFrameworkImpl - Background operation retry gave up
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkBackgroundRetry(CuratorFrameworkImpl.java:728)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:857)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:809)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:64)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:267)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
18:19:00.507 logback [Curator-Framework-0] ERROR o.a.c.f.imps.CuratorFrameworkImpl - Background retry gave up
org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:838)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:809)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:64)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:267)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
18:19:01.104 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server 192.168.144.130/192.168.144.130:2181. Will not attempt to authenticate using SASL (unknown error)
18:19:01.183 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.NoRouteToHostException: No route to host: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
18:19:02.289 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server 192.168.144.130/192.168.144.130:2181. Will not attempt to authenticate using SASL (unknown error)
18:19:02.296 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.NoRouteToHostException: No route to host: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
18:19:03.430 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server 192.168.144.130/192.168.144.130:2181. Will not attempt to authenticate using SASL (unknown error)
18:19:03.565 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] INFO  org.apache.zookeeper.ClientCnxn - Socket connection established to 192.168.144.130/192.168.144.130:2181, initiating session
18:19:03.606 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] INFO  org.apache.zookeeper.ClientCnxn - Session establishment complete on server 192.168.144.130/192.168.144.130:2181, sessionid = 0x1000005358d0586, negotiated timeout = 40000
18:19:03.606 logback [Curator-Framework-0-EventThread] INFO  o.a.c.f.state.ConnectionStateManager - State change: RECONNECTED
19:33:00.825 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x1000005358d0586 for server 192.168.144.130/192.168.144.130:2181, unexpected error, closing socket connection and attempting reconnect
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:68)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
19:33:01.063 logback [Curator-Framework-0-EventThread] INFO  o.a.c.f.state.ConnectionStateManager - State change: SUSPENDED
19:33:02.024 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server 192.168.144.130/192.168.144.130:2181. Will not attempt to authenticate using SASL (unknown error)
19:33:02.028 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x1000005358d0586 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.NoRouteToHostException: No route to host: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
19:33:03.393 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server 192.168.144.130/192.168.144.130:2181. Will not attempt to authenticate using SASL (unknown error)
19:33:03.394 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x1000005358d0586 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.NoRouteToHostException: No route to host: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
20:28:10.614 logback [Curator-Framework-0] WARN  org.apache.curator.ConnectionState - Connection attempt unsuccessful after 3309504 (greater than max timeout of 60000). Resetting connection and trying again with a new connection.
20:28:11.562 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server 192.168.144.130/192.168.144.130:2181. Will not attempt to authenticate using SASL (unknown error)
20:28:11.565 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] WARN  org.apache.zookeeper.ClientCnxn - Client session timed out, have not heard from server in 3308069ms for sessionid 0x1000005358d0586
20:28:11.714 logback [Curator-Framework-0] INFO  org.apache.zookeeper.ZooKeeper - Session: 0x1000005358d0586 closed
20:28:11.715 logback [Curator-Framework-0] INFO  org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=192.168.144.130:2181 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@12010fd1
20:28:11.715 logback [Curator-Framework-0-EventThread] INFO  org.apache.zookeeper.ClientCnxn - EventThread shut down for session: 0x1000005358d0586
20:28:11.923 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server 192.168.144.130/192.168.144.130:2181. Will not attempt to authenticate using SASL (unknown error)
20:28:11.930 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.NoRouteToHostException: No route to host: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
20:28:12.747 logback [Curator-Framework-0] ERROR o.a.c.f.imps.CuratorFrameworkImpl - Background operation retry gave up
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkBackgroundRetry(CuratorFrameworkImpl.java:728)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:857)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:809)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:64)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:267)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
20:28:12.748 logback [Curator-Framework-0] ERROR o.a.c.f.imps.CuratorFrameworkImpl - Background retry gave up
org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:838)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:809)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:64)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:267)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
20:28:13.112 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server 192.168.144.130/192.168.144.130:2181. Will not attempt to authenticate using SASL (unknown error)
20:28:13.118 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.NoRouteToHostException: No route to host: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
20:28:14.276 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server 192.168.144.130/192.168.144.130:2181. Will not attempt to authenticate using SASL (unknown error)
20:28:14.998 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] INFO  org.apache.zookeeper.ClientCnxn - Socket connection established to 192.168.144.130/192.168.144.130:2181, initiating session
20:28:15.029 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] INFO  org.apache.zookeeper.ClientCnxn - Session establishment complete on server 192.168.144.130/192.168.144.130:2181, sessionid = 0x1000005358d059b, negotiated timeout = 40000
20:28:15.030 logback [Curator-Framework-0-EventThread] INFO  o.a.c.f.state.ConnectionStateManager - State change: RECONNECTED
23:43:00.955 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x1000005358d059b for server 192.168.144.130/192.168.144.130:2181, unexpected error, closing socket connection and attempting reconnect
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:68)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
23:43:01.147 logback [Curator-Framework-0-EventThread] INFO  o.a.c.f.state.ConnectionStateManager - State change: SUSPENDED
23:43:02.615 logback [Curator-Framework-0-SendThread(192.168.144.130:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server 192.168.144.130/192.168.144.130:2181. Will not attempt to authenticate using SASL (unknown error)
